### ISSUE TITLE
DIffferent Versions of Vitovent 300W

### ISSUE THREAD

**Issue by challo2018** [apdlv72/VitoWifi#1]
Hi, can someone give me datails about exact version of working 300w?
It seems that OpenTherm is not activated on mine :-(
Is it necessary to have the control panel connected on OT? Actually i have no control panel connected due the vitovent is connected to my Vitocal via Modbus.
Can you also give me hint (Art. Number etc) of your controll panel if this is necessary. Is it LB1?

Thanks!
BR Fabian

**Comment by apdlv72** [comment]
Hi Fabian.

I am German, feel free to reply in German if you are capable of speaking it.

I have no idea what different versions Viessman produced in the past and I found
by incident that mine (built 2009) is OpenTherm-enabled when I opened the 
remote control and stumbled over a small “OT” printed next to the screw terminator 
that connects to the 2-wire line.

Also, I don't know the exact manufacturer code but it’s the same depicted here:
https://www.heizsystemshop.de/lueftungen/fernbedienung-vitovent-300.html

I don’t know if it’s possible to connect this kind of controller to YOUR Vitovent,
but I am wondering why you would like to do so???

Actually the VitoWifi project aims at connecting “somehow” to a Vitovent which
does not provide such connectivity out of the box.

When your’s has Modus already … why don’t you use that?
What exactly are you trying to achieve?

Greetings from Cologne.

Artur Pogoda de la Vega
apdlv72@gmail.com

**Comment by challo2018** [comment]
Hi Artur, 
danke für deine Antwort. Meine Vitovent 300W ist aus dem Jahr 2017. 
Von meinem Heizungsbauer wurde empfohlen diese über Modbus mit der Steuerung meiner Wärmepumpe zu verbinden. Jetzt kann ich an der Wärmepumpe auch die Lüftung steuern. Eine Einbindung in mein Loxone smarthome ist allerdings nicht möglich. werder bei der wärmepumpe noch bei der lüftung. für die Wärmepume gibt es für ca. 1000€ ein KNX gateway. Damit kann allerdings nicht auf die Lüftung zugegriffen werden. Ich habe ein OTGW hier liegen und die Platine hat auch weiterhin diesen 2 Draht anschluss. Allerdings ist dieser nicht mehr mit OT sondern mit "Bedienteil (2-poliger Stecker, Adern vertauschbar,X1.1/X1.2) beschrieben. Ich habe dieses Bedienteil leider nicht. Wenn ich dort den OTGW anschließe bekomme ich keine Daten. Für eine direkte Ansteuerung über Modbus habe ich bisher noch keine Dokumentation oder ähnlich gefunden. 
"

**Comment by apdlv72** [comment]
Hi Fabian.

Deutsch macht die Kommunikation deutlich einfacher :-)

Kannst du Mal ein Bild der Platine schicken? Ich bin ein wenig verwirrt,
welche du meinst. Die des otgw? Oder des beckenteils? Welches du ja gar
nicht hast?

Wenn deine Wärmepumpe Modbus kann aber du noch nicht rausgefunden hast, wie
genau deine Lüftung per Modbus abgesprochen werden kann, nutzt dir
vermutlich mein Projekt wenig.

Modbus würde ich in jedem Fall vorziehen. Otgw ist nur eine Notlösung um
eine Lüftung einzubinden, die nichts anderes spricht.

Ob da trotzdem ein Signal anliegt oder nicht... Wie hast du das
rausgefunden? Weisst du, dass dein otgw funktioniert? Hast du es selbst
gelötet?

Verrat mir Mal, wo du wohnst. Ich komme aus Köln. Evtl. können wir Mal mein
definitiv funktionierendes otgw bei dir anschließen?

Gruss, Artur

Am Di., 20. Nov. 2018, 15:44 hat Artur Pogoda de la Vega <apdlv72@gmail.com>
geschrieben:

>
> Hi Fabian.
>
> I am German, feel free to reply in German if you are capable of speaking
> it.
>
> I have no idea what different versions Viessman produced in the past and I
> found
> by incident that mine (built 2009) *is* OpenTherm-enabled when I opened
> the
> remote control and stumbled over a small “OT” printed next to the screw
> terminator
> that connects to the 2-wire line.
>
> Also, I don't know the exact manufacturer code but it’s the same depicted
> here:
> https://www.heizsystemshop.de/lueftungen/fernbedienung-vitovent-300.html
>
> I don’t know if it’s possible to connect this kind of controller to YOUR
> Vitovent,
> but I am wondering why you would like to do so???
>
> Actually the VitoWifi project aims at connecting “somehow” to a Vitovent
> which
> does not provide such connectivity out of the box.
>
> When your’s has Modus already … why don’t you use that?
> What exactly are you trying to achieve?
>
> Greetings from Cologne.
>
> Artur Pogoda de la Vega
> apdlv72@gmail.com
>
>
>

**Comment by challo2018** [comment]
Hi, 
ja auf jeden Fall ;-) Ich mache morgen oder spätestens Freitag ein Bild von der Platine in meiner Vitovent.
Ein Bedienteil habe ich bisher nicht...

Klar, bei der Modbus Verbindung komme ich mit deinem Projekt nicht weiter. Allerdings finde ich zu der Viessmann Modbus Schnittstelle gar keine Informationen im Internet. Es gibt von Brink und Wolf baugleiche Geräte, allerdings benötigen diese ein extra Modbus-Modul. 

Den OTGW habe ich gelötet bestellt. Nur das NodeMCU habe ich aufgesetzt. In der Weboberfläche werden keine Daten angezeigt. Ich werde das am Wochenende nochmal prüfen. 

Ich komme aus der nähe von Idar-Oberstein. Vielleicht wäre es auch eine Möglichkeit dir mein Gateway zu schicken, da bei dir sicher OT aktiviert ist. 

Melde mich nochmal mit Bildern der Platine. dann können wir ja mal vergleichen. 

Gruß Fabian

**Comment by apdlv72** [comment]
Hallo Fabian.

Bei näherem Nachdenken ist mir klar geworden, dass Du gar keine Daten sehen KANNST,
wenn Du nur das OTGW an Deine Lueftung haengst aus folgendem Grund:

Das OTGW haengt ja im Prinzip nur zwischen dem Bedienter und dem Lueftungsgeraet und
schiebt die Befehle nur hin und her.

Die Lueftung (hier Slave) schickt von sich aus überhaupt keine Kommandos auf die Leitung sondern
beantwortet im Prinzip nur die Kommandos vom Bedienteil (hier Master).
Das einzige, was das OTGW in diesem Szenario fuer dich tun kann, ist es, den Befehl vom Master, 
der die Lueftungsstufe bestimmt, so zu ersetzen, bevor es ihn weitergibt, dass die eingestellte
Luefterstufe durch eine andere ersetzt wird, die Du gerne stattdessen hättest und die Du von aussen
im OTGW setzt.

Wenn Du mir Dein OTGW schicktest, koennte ich zwar ausprobieren, ob es prinzipiell funktioniert,
damit ware Dir aber nicht weitergeholfen, weil es von sich aus nicht das Bedienteil ersetzt, 
sondern wie oben beschrien nur man-in-the-middle spielt.

Da Du eine NodeMCU besitzt und anscheinend des Loetens mächtig bist, könntest Du was anderes 
probieren. Ich stehe im Kontakt mit einem Nutzer, der ein ähnliches Ziel hat. Er besitzt eine Vitivent,
die definitiv OpenTherm spricht, aber er hat auch kein Bedienteil und möchte es durch einen ESP8266
ersetzen.
Er hat auch schon das Beispiel “master” aus folgendem Projekt an seiner Vitovent erfolgreich ausprobiert:
https://github.com/jpraus/arduino-opentherm/tree/master/examples/master

Allerdings nur mit einem Arduino, d.h. ohne Wifi-Anbindung.
Leider lässt sich das Beispiel nicht mit dem ESP kompilieren, weil die Initialisierung der Interrupt-Routinen
da ganz anders funktioniert. Weil er damit keine Erfahrung hatte, hat er ich um Hilfe gebeten.

Es gibt ein anderes Projekt, das  auf dem ESP kompiliert (sogar auf dem ESP-32), allerdings kann/konnte 
das nicht eine Lueftung steuern, sondern nur den Thermostat fuer einen Boiler simulieren:
https://github.com/ihormelnyk/opentherm_library <https://github.com/ihormelnyk/opentherm_library>

Da ich es viel einfacher fand, Beil letzterem die nötigen Befehle/Funktionen hinzuzufügen, als das erste
Projekt zu Portieren, habe ich das getan:
https://github.com/apdlv72/opentherm_library/tree/master/examples/VentilationMaster <https://github.com/apdlv72/opentherm_library>

Allerdings ist es gänzlich ungetestet. Ich habe nur das Original-Projekt geformt und erweitert.
Im Prinzip werden die nötigen Kommandos geschickt, allerdings wird vermutlich noch Feinarbeit nötig sein.
Ich kann das leider noch nicht testen, weil ich noch auf die Interface-Platine warte. Sie ist auf dem Postweg
aus der Ukraine und das kann leider etwas dauern.
(http://ihormelnyk.com/opentherm_adapter <http://ihormelnyk.com/opentherm_adapter>)

Im Prinzip muesstest Du diese aber gar nicht haben, um zu Testen, ob deine Lueftung Kommandos 
schickt oder nicht. Die Platine implementiert im Prinzip nur den Lueftings-seitigen Teil des OTGW, d.h.
kann Kommandos schickt und empfangen, nicht aber zum Bedienteil.

Wenn Du den PIC auf dem OTGW herausziehst (ist hoffentlich gesuckelt?), könntest Du Deine NodeMCU
an den entsprechenden Stellen per Dupont-Kabel einstecken und mit meinem Beispiel versuchen, 
Bedienteil zu spielen, um zu sehen, ob Die Kommandos ueberhaupt beantwortet werden.
Vorausgesetzt, Du hast Dich nicht verlötet beim OTGW und Deine Lueftung spricht OT, muesstest die
im Prinzip schon Antworten sehen koennen, ohne dass Du irgendwas neu anschaffen musst.

Falls das funktioniert, kannst Du entweder das OTGW, was Du eh schon gekauft hast, statt mit dem
PIC mit dem NodeMCU betreiben oder Du kannst Dir den o.g. Opentherm Adapter bestellen oder selbst 
loeten. Das sind nur wenige billige Bauteile, die schnell auf einer Lochrasterplatine zusammengelötet sind.
Da ich momentan zu wenig Zeit habe, hab ich mir das bequemerweise bei Ihor bestellt.

VG

Artur Pogoda de la Vega
apdlv72@gmail.com

**Comment by arnolde** [comment]
Hallo, sorry wenn ich hier so reinplatze ;-) ich hab gerade diese Woche meine ESP mittels Ihor's Library (manuell um einige Lüftungs-Parameter ergänzt) und Ihor's OT Interface geschafft, meine WOLF CWL 300 (baugleich Vitovent) anzusteuern und auszulesen. Momentan kann ich die Lüfterstufen 0,1,2,3 schalten oder auch die rel.lüfterleistung von 20%-95% stufenlos einstellen.

Was ich noch nicht geschafft hab ist die Filteranzeige auszulesen (wobei ich jetzt hier gelesen hab daß das TSP (Id 89) Nummer 0x17 sein soll, 1 ist offenbar "filter ok", mal sehen was meiner grad sagt, bei dem ist grad die Filteranzeige an. Ausserdem den Bypass noch ansteuern (da ich einen Erdwärmetauscher hab, will ich den Bypass im Sommer aus haben um kühle Luft reinzuziehen). Und perfekt wäre wenn ich den Lüfter auch unterhalb 20% noch einstellen könnte, damit ich im Winter bei trockener Luft eine noch minimalere Lüftung haben kann.

viele Grüße,
Ethan

**Comment by arnolde** [comment]
Seltsam, ich hab grad alle 64 TSP's ausgelesen und erhalte für 0,2,4: 0x64, 0x96 und 0x2c - das passt aber nicht zu den tatsächlichen Ergebnissen wenn ich die Stufen 1/2/3 aktiviere dann sind die ausgelesenen Drehzahlen: 0x24, 0x39 und 0x5f.

Hier sind meine TSP Werte: (Hi = Key, Lo = Value)
Requesting TSP Parameters:
0064, 0100, 0296, 0300, 042C, 0501, 0614, 0738,
0800, 0901, 0A00, 0B6E, 0C01, 0D02, 0E00, 0F02,
1003, 1101, 1201, 1302, 1400, 1500, 163D, 1701,
1800, 1900, 1A01, 1B03, 1C3C, 1D00, 1E00, 1F00,
2000, 2150, 2250, 2300, 2400, 2501, 2600, 2700,
2801, 2908, 2A0A, 2B00, 2C04, 2D0A, 2E00, 2F00,
30F5, 3100, 3232, 3300, 3432, 3500, 3600, 376F,
387A, 3901, 3A00, 3B00, 3C45, 3D00, 3E45, 3F00

**Comment by madmax75** [comment]
> Hallo, sorry wenn ich hier so reinplatze ;-) ich hab gerade diese Woche meine ESP mittels Ihor's Library (manuell um einige Lüftungs-Parameter ergänzt) und Ihor's OT Interface geschafft, meine WOLF CWL 300 (baugleich Vitovent) anzusteuern und auszulesen. Momentan kann ich die Lüfterstufen 0,1,2,3 schalten oder auch die rel.lüfterleistung von 20%-95% stufenlos einstellen.
> 
> 
> 
> Was ich noch nicht geschafft hab ist die Filteranzeige auszulesen (wobei ich jetzt hier gelesen hab daß das TSP (Id 89) Nummer 0x17 sein soll, 1 ist offenbar "filter ok", mal sehen was meiner grad sagt, bei dem ist grad die Filteranzeige an. Ausserdem den Bypass noch ansteuern (da ich einen Erdwärmetauscher hab, will ich den Bypass im Sommer aus haben um kühle Luft reinzuziehen). Und perfekt wäre wenn ich den Lüfter auch unterhalb 20% noch einstellen könnte, damit ich im Winter bei trockener Luft eine noch minimalere Lüftung haben kann.
> 
> 
> 
> viele Grüße,
> 
> Ethan

Hallo Ethan,
ich betreibe ebenfalls eine Wolf CWL 300 und würde diese gerne per OTGW auslesen. Ich habe ein Gateway mit NodeMCU hier bei mir liegen und habe versucht mit dieser die KWL anzubinden. Leider vergeblich. Gibt es eine Anleitung wie die genaue Vorgehensweise ist um die Verbindung herzustellen?

**Comment by apdlv72** [comment]
Hallo madmax75!

Was genau hast du denn versucht und was hat nicht geklappt? Da du das Gateway ja schon fertig da liegen hast (Bausatz selbst zusammen gelötet oder fertig gekauft?), sollte das Anschließen selbst ja relativ unproblematisch sein: Kabel zur Lüftung an die eine klemme, Kabel zum Controller an die andere. 

Danach muss vermutlich noch auf den PIC des otgw die aktuelle Software aufgespielt werden und anschließend auf dem mcu deine eigene Lösung oder z.B. mein vitowifi, um mit dem otgw zu kommunizieren, um den aktuellen Status verfügbar (WLAN) zu machen oder die Lüfterstufen zu beeinflussen.

VG
Artur

**Comment by madmax75** [comment]
> Hallo madmax75!
> 
> Was genau hast du denn versucht und was hat nicht geklappt? Da du das Gateway ja schon fertig da liegen hast (Bausatz selbst zusammen gelötet oder fertig gekauft?), sollte das Anschließen selbst ja relativ unproblematisch sein: Kabel zur Lüftung an die eine klemme, Kabel zum Controller an die andere.
> 
> Danach muss vermutlich noch auf den PIC des otgw die aktuelle Software aufgespielt werden und anschließend auf dem mcu deine eigene Lösung oder z.B. mein vitowifi, um mit dem otgw zu kommunizieren, um den aktuellen Status verfügbar (WLAN) zu machen oder die Lüfterstufen zu beeinflussen.
> 
> VG
> Artur

Hallo Artur,

> Danach muss vermutlich noch auf den PIC des otgw die aktuelle Software aufgespielt werden und anschließend auf dem mcu deine eigene Lösung oder z.B. mein vitowifi, um mit dem otgw zu kommunizieren, um den aktuellen Status verfügbar (WLAN) zu machen oder die Lüfterstufen zu beeinflussen.

Ganau hier komme ich nicht weiter. Wie bekomme ich die die aktuelle Software auf das Gateway und welche muss ich genau nehmen? 
Stehe da gerade total auf dem Schlauch.

VG 
Andre

**Comment by apdlv72** [comment]
Hallo Andre!

Ist schon ein paar Jahre her, seit ich das gemacht habe. Mein otgw läuft
seit ca. 4 Jahren bei mir.

Aber wenn ich mich recht entsinne, dann kam mein PIC auf dem otgw (habe
Bausatz selbst gelötet) nur mit einer disgnose-software zum Testen der
Verbindungen zu Lüftung und Controller.

Mit der Software (damals nur Windows) könnte ich mich per USB/seriell
Wandler zum otgw verbinden und da gab ein einen Menüpunkt zum flashen eines
neuen Images für den Pic.

Ich habe das neueste damals verfügbare Image genommen und damit hat es
funktioniert.

Wenn ich mich nicht irre, haengt an deinem rs232 Ausgang des Pics ja aber
die mcu, richtig? Ich vermute, den musst du erst Mal abstoepseln und den
Pic an deinen PC verbinden um die Firmware aufzuspielen.

Wenn du dann die Firmware drauf hast, solltest du die Kommunikation in dem
Monitor Programm sehen können.

Danach kannst du dann die mcu wieder anschließen und dort aufspielen, was
auch immer du mit dem otgw machen möchtest. Ob das nun vitowifi ist oder
den mcu im Auslieferungszustand - wo er i.d.R. nur eie einfache
seriell-nach-wifi Brücke darstellt.

Alle Angaben wie gesagt ohne Gewähr. Ich weiss nicht, was genau du da vor
dir liegen hast, aber ich hoffe ich konnte dir ein wenig weiterhelfen.

VG Artur

PS: wo wohnst du? Vielleicht ja gar nicht so weit entfernt? Ich wohne in
Frechen bei Köln


MadMax <notifications@github.com> schrieb am So., 3. Mai 2020, 15:43:

**Comment by madmax75** [comment]
Hallo Artur,
vielen Dank für Deine Infos. Ich habe jetzt erfolgreich die PIC und die nodemcu flashen können und bekomme nun auch die Webseite angezeigt. 
Ich habe nun noch keine Info gefunden wie ich meine FB mit dem OTGW verbinden muss(welche Klemmbelegung).

Gruss
André

**Comment by gzin** [comment]
Hallo Artur!
Ich habe auch eine Wolf CWL 300 und das Gateway von Shelte Brom. Wenn ich den Ethernet-Aufsatz aufstecke, dann kann ich per serieller (Netzwerk-)Verbindung schon wunderbar mitlesen: nach dem Befehl "GW=1" schickt er zyklisch ein paar Befehle hin und bekommt Antwort. Leider wechselt die CWL immer zwischen 0 ("ferngesteuert") und 1 ("Wahlschalter"). Wenn ich dann den Befehl "GW=0" sende, ist die Anlage wieder dauerhaft im Wahlschalter-Modus. (eine inkludierte Fernsteuerung über OpenTherm habe ich nicht)
Spiele ich die Software von dir auf den NodeMCU (auf derselben Platine wie der PIC; statt dem Ethernet-Modul), dann beobachte ich dieses zyklische Umschalten zwischen 0 und 1 ebenfalls. Also nehme ich an, dass die Ansteuerung funktioniert (zumindest "GW=1"). 
Ich habe noch vom Betrieb über das Arduino-Terminal gesehen, dass da Befehle wie ZZ=r oder oder ZZ=wwww gesendet werden. Sollte die Firmware das können? Wenn ich mir die Befehle so ansehe, steht da nichts von "ZZ" drinnen:
http://otgw.tclcode.com/firmware.html#configuration
Verwende ich die falsche Firmware? (ich habe die aktuellste eingespielt) Ist der Befehl "ZZ" bei der neuen Firmware raus geflogen?

Alterntiv habe ich mir das Modul aus der Ukraine (http://ihormelnyk.com/opentherm_adapter) samt Adapter für D1-Mini (ESP8266) bestellt und bekommen. Hier komme ich aber auch nicht weiter, weil ich noch beim Programmieren hänge.

Habt ihr eine Idee, wie ich mit dem OTGW weiter machen kann?

Gruß
Günther

**Comment by apdlv72** [comment]
No action anymore

**Comment by apdlv72** [comment]
Closing

**Comment by gzin** [comment]
Inzwischen läuft das Modul mit dem D1-Mini recht gut, ich kann die Lüftungsstärke steuern und auch alle Register auslesen.

Was noch nicht klappt ist die Steuerung des Bypasses und das Auslesen der Filter-Alarms. Hat da jemand eine Idee?

Gruß
Günther
