### ISSUE TITLE
AP wird nicht gefunden

### ISSUE THREAD

**Issue by Xtianlpz** [apdlv72/VitoWifi#2]
Hallo Artur.

Ich habe meinen ESP8266 NodeMCU erfolgreich mit deinem Projekt geflasht, sehe die SSID nun aber nicht im WLAN. Ich mache sicherlich nur was sehr triviales falsch. Aber was?

**Comment by apdlv72** [comment]
No action. Closing

**Comment by apdlv72** [comment]
Close
