### ISSUE TITLE
cant connect to ap

### ISSUE THREAD

**Issue by crazypaddo** [apdlv72/VitoWifi#3]
hello sir, i have a brink wtw ventilation unit.(same as vitovent)
i have 2 otgw interfaces, 
i first used off 1 otgw only the boiler part to connect to a arduino mega as a master with the opentherm library to send commands to  the wtw unit.
this works because i can turn the unit on and off and set the relative ventilation value. 
So data is flowing between the master and slave. 
now i have programmed a nodemcu v3 with your project. so far so good.
i see the ssid apear when i want to connect to the network http://192.168.4.1 and i see something about tokken created in the debug terminal.
i open my webbrowser and go to http://192.168.4.1 type VitoWifi and password 12345678 and hit connect.
but when i look at the debug terminal from the esp i see error 4 and the page counts down and times out?
but the data from my arduino mega master gets true the gateway because the ventilation units stays in opentherm modus 
and when i change the send data id in the master the unit changes the value.(speeds up / slows down ventilation motors).
but i am not an expert in programming and cant seem to figure out whats the problem.
could it be due to me turning aldataids on? because i got some errors in arduino while compiling about dupicated case entrys?
i commented the out,and it compiled without errors. but maybee i broke something wyle doing this.
i hope you an guide me in the write direction. so i can save a lot off monney on my heating bill that my heat provider want from me to heat a small appartment.
regards marco van oort

**Comment by apdlv72** [comment]
No action. Closing

**Comment by apdlv72** [comment]
Close
