### ISSUE TITLE
Any known solution for connecting via modbus?

### ISSUE THREAD

**Issue by thilasx** [apdlv72/VitoWifi#4]
Hey there! 
Thanks for sharing your solution for the vitovent with OT protocol.
I'd like to ask if you know a solution for reading the sensors and configuring the vent via modbus?
I searched the net yesterday but was only able to find that viessmann is most likely buying their vent solutions from another manufacturer called brink and that some people were able to use a modbus adapter but weren't able to connect successfully.
Therefore, because you mentioned in another issue that you would prefer modbus, I thought you might know a way.

**Comment by apdlv72** [comment]
No, don't know anything about modbus. And cannot test because my unit is not modbus based.
