### ISSUE TITLE
Fehlermeldung beim Kompilieren

### ISSUE THREAD

**Issue by madmax75** [apdlv72/VitoWifi#5]
Hi @apdlv72,
ich wollte die aktuelle Version auf meine nodemcu per Arduino IDE aufspielen, erhalte jedoch die folgende Fehlermeldung:

In file included from /Users/andre/Documents/Arduino/ESP_VitoWifi/ESP_VitoWifi.ino:175:
/Users/andre/Documents/Arduino/ESP_VitoWifi/OTMessage.h: In static member function 'static String OTMessage::msgTypeToStr(uint8_t)':
/Users/andre/Documents/Arduino/ESP_VitoWifi/OTMessage.h:48:5: error: control reaches end of non-void function [-Werror=return-type]
   48 |     }
      |     ^
cc1plus: some warnings being treated as errors

exit status 1

Compilation error: control reaches end of non-void function [-Werror=return-type]

**Comment by apdlv72** [comment]
Hi.

Welche Arduino version? Ich habe das seit Dezember nicht mehr gebaut. Da
fehlt wohl ein Return in der Funktion wie zb return "" am Ende der
Funktion.

Falls du es selbst hinbekommst, mache gerne einen pull request. Ansonsten
melde dich nochmal. Ist bestimmt kein biggie.

Gruß,
Artur

**Comment by madmax75** [comment]
Hi @apdlv72 ,
ich habe es mit Arduono IDE 2.1.0 versucht und es leider mit deiner Anweisung nicht hinbekommen. Könntest du dir das netterweise mal anschauen?
LG André

**Comment by madmax75** [comment]
> Hi Artur,
> ich habe es mit Arduono IDE 2.1.0 versucht und es leider mit deiner Anweisung nicht hinbekommen. Könntest du dir das netterweise mal anschauen?
> LG André

**Comment by apdlv72** [comment]
Hall Andre.
Ich verstehe nicht, wie der jetztige Stand ist. Compiliert es jetzt bei Dir oder immer noch nicht?
Habe gesehen, dass Du den Request geschlossen und sofort wieder geoeffnet hast.
VG, Artur

**Comment by madmax75** [comment]
Hallo @apdlv72,
leider erhalte ich beim kompilieren die oben genannte Fehlermeldung. Hatte aus Versehen den Request geschlossen.
VG
Andre

**Comment by apdlv72** [comment]
Hallo Andre!
Welche Fehlermeldung? Die urspruengliche? (control reaches end of non-void function)
Hast Du denn neu gepullt nachdem ich das letzten Monat gefixt hatte?
Der aktuelle Code sieht so aus - siehe unten.
In der Zeile 48 ist jetzt vorher fehlende der Default-Rueckgabewert, ueber den sich der Compiler beschwert hat.
Wie bereits geschrieben, habe ich das _auch_ mit der Version 2.1.0. der IDE erfolgreich kompilieren koennen.
VG, Artur

37 static String msgTypeToStr(uint8_t t) {
38      switch(t) {
39        case MT_READ_DATA:    return "READ_DATA";
40        case MT_WRITE_DATA:   return "WRITE_DATA";
41        case MT_INVALID_DATA: return "INVALID_DATA";
42        case MT_RESERVED:     return "RESERVED";
43        case MT_READ_ACK:     return "READ_ACK";
44        case MT_WRITE_ACK:    return "WRITE_ACK";
45        case MT_DATA_INVALID: return "DATA_INVALID";
46        case MT_UNKN_DATAID:  return "UNKN_DATAID";
47      }
48      return "UNKNOWN";
49    }

**Comment by madmax75** [comment]
Hi @apdlv72,
ich habe es nun am Laufen. Besten Dank.
Wie kann ich nach dem Setup den Access Point Modus "AP_VitoWifi" abschalten, sodass dieser nicht mehr sichtbar ist?

Gruß
Andre

**Comment by apdlv72** [comment]
Hi @madmax75 !

Versuche es mal in folgender Zeile 
https://github.com/apdlv72/VitoWifi/blob/master/ESP_VitoWifi.ino#L885
EE.accessPoint.used = 0 zu setzten.
Das ist aber ohne Gewaehr. Ich habe bei mir den AP Modus immer aktiviert,
um z.B. bei einem Router-Wechsel das Passwort aendern zu koennen ohne
dass ich den ESP ausbauen muss.

Du kannst auch in diese Zeile:
https://github.com/apdlv72/VitoWifi/blob/master/ESP_VitoWifi.ino#L1775
Fest den AP ausschalten mit: 
WiFi.mode(WIFI_STA);

VG,
Artur
